application: aegissurv
version: 1
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "1m"





handlers:
#tasks and cronjobs
- url: /tasks.*
  script: tasks.app
  login: admin
- url: /cronjobs.*
  script: cron_jobs.app
  login: admin
  

- url: /img
  static_dir: img
- url: /css
  static_dir: css
- url: /js
  static_dir: js


- url: /
  script: landing.app
- url: /upload.*
  script: upload.app
  secure: always
- url: /view.*
  script: view.app
- url: /photo.*
  script: photo.app
- url: /signup
  script: signup.app
- url: /link
  script: link.app
- url: /login
  script: login.app
- url: /logout
  script: logout.app
- url: /password
  script: password.app
- url: /alert.*
  script: alert.app
  
- url: /admin.*
  script: admin.app
  login: admin


libraries:
- name: jinja2
  version: latest
- name: pycrypto
  version: 2.3

builtins:
- appstats: on
- deferred: on


skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?.psd
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^boto/
- ^Crypto/
